TOOL_DESCRIPTIONS = {
    "asset": {
        "keywords": ["photo", "video", "asset", "media", "image"],
        "tools": [
            "get_asset_info",
            "search_metadata",
            "search_smart",
            "search_random",
            "run_asset_jobs",
            "get_faces",
            "create_face",
            "delete_face",
            "reassign_faces_by_id",
        ],
    },
    "album": {
        "keywords": ["album", "gallery", "collection"],
        "tools": [
            "get_all_albums",
            "create_album",
            "get_album_info",
            "delete_album",
            "add_assets_to_album",
            "remove_assets_from_album",
        ],
    },
    "people": {
        "keywords": ["person", "people", "face", "who"],
        "tools": [
            "search_people",
            "get_all_people",
            "get_person",
            "get_person_statistics",
            "get_person_thumbnail",
            "create_person",
            "update_people",
            "delete_people",
            "update_person",
            "delete_person",
            "merge_person",
            "reassign_faces",
        ],
    },
    "place": {
        "keywords": ["place", "location", "where", "map"],
        "tools": ["search_places", "get_search_suggestions"],
    },
    "memory": {
        "keywords": ["memory", "memories", "moment"],
        "tools": [
            "search_memories",
            "create_memory",
            "get_memory_statistics",
            "get_memory",
            "update_memory",
            "delete_memory",
            "add_memory_assets",
            "remove_memory_assets",
        ],
    },
    "user_admin": {
        "keywords": ["user administration", "admin", "manage users"],
        "tools": [
            "search_users_admin",
            "create_user_admin",
            "get_user_admin",
            "update_user_admin",
            "delete_user_admin",
            "restore_user_admin",
            "get_user_preferences_admin",
            "update_user_preferences_admin",
            "get_user_statistics_admin",
            "sign_up_admin",
        ],
    },
    "user": {
        "keywords": ["user", "me", "my account", "profile"],
        "tools": [
            "search_users",
            "get_my_user",
            "update_my_user",
            "get_user",
            "delete_user_license",
            "get_user_license",
            "set_user_license",
            "delete_user_onboarding",
            "get_user_onboarding",
            "set_user_onboarding",
            "get_my_preferences",
            "update_my_preferences",
            "delete_profile_image",
            "create_profile_image",
            "get_profile_image",
        ],
    },
    "auth": {
        "keywords": [
            "authentication",
            "authorization",
            "security",
            "login",
            "password",
        ],
        "tools": [
            "get_api_keys",
            "create_api_key",
            "get_api_key",
            "update_api_key",
            "delete_api_key",
            "change_password",
            "login",
            "logout",
            "reset_pin_code",
            "setup_pin_code",
            "change_pin_code",
            "lock_auth_session",
            "unlock_auth_session",
            "get_auth_status",
            "validate_access_token",
        ],
    },
    "sharing": {
        "keywords": ["sharing", "share", "link", "public"],
        "tools": [
            "get_all_shared_links",
            "create_shared_link",
            "get_my_shared_link",
            "get_shared_link_by_id",
            "remove_shared_link",
            "update_shared_link",
            "remove_shared_link_assets",
            "add_shared_link_assets",
        ],
    },
    "system": {
        "keywords": ["system", "job", "status", "server"],
        "tools": ["get_all_jobs_status", "send_job_command"],
    },
}
